config/routes.rb
Rails.application.routes.draw do
  root to: 'tickets#new'
  resources :tickets
  resources :shows
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  belongs_to :show
  belongs_to :ticket
end

app/models/show.rb
class Show < ActiveRecord::Base
  has_many :tickets, dependent: :destroy
  has_many :seats, dependent: :destroy
  after_commit :add_seats

  def add_seats
    (1..10).each do |row|
      (1..10).each do |seat|
        seats << Seat.create(row: row, place: seat, availability: true)
      end
    end
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :seat
  belongs_to :show

  validates_presence_of :user_name, :show_id, :seat_id
  validate :seat_availability

  def seat_availability
    errors.add(:seat_id, "Seat is occupied") if !seat.availability
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  layout 'application'

  def show
    @ticket = Ticket.find(params[:id])
  end

  def new
    @ticket = Ticket.new
    @shows = Show.all
  end

  def create
    seat_cred = params[:ticket][:seat_id].split('/')
    @show = Show.find(params[:ticket][:show_id])
    @seat = @show.seats.where(row: seat_cred[0].to_i, place: seat_cred[1].to_i).first
    @ticket = Ticket.new(
      show_id: @show.id,
      seat_id: @seat.id,
      user_name:  params[:ticket][:user_name]
      )
    if @ticket.valid?
      @ticket.save
      @seat.availability = false
      @seat.save
      redirect_to ticket_path(@ticket), flash: { success: 'You acquired a ticket!' }
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Lab6Pw
    = stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true

    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    %link{:href => "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", :rel => "stylesheet"}/
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"}
    %script{:src => "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"}
    = csrf_meta_tags
  %body
    = yield

app/views/tickets/_row.html.haml
%tr
  %td.row-number=row
  - (1..10).each do |i|
    - if(i == 5)
      %td.center
    - else
      %td.available

app/views/tickets/new.html.haml
.seats
  %h2#show_name Please select a show
  %table
    %tbody
      - (1..10).each do |i|
        = render partial: 'row', locals: { row: i}
.user-form
  = simple_form_for @ticket, url:  tickets_path, html: { class: 'form-horizontal' } do |f|
    .form-inputs
      .form-group
        .row
          .col-md-3
            %label.text.optional{:for => "show_id"} Select show:
          .col-md-6
            = f.collection_select :show_id, Show.all, :id, :name, required: true, label: false
        .row
          .col-md-3
            %label.text.optional{:for => "user_name"} Name:
          .col-md-6
            = f.input :user_name, required: true, label: false
        .row
          .col-md-3
            %label.text.optional{:for => "seat_id"} Seat:
          .col-md-6
            = f.input :seat_id, as: :string, required: true, label: false, input_html: { value: params[:ticket].nil? ? '' : "#{params[:ticket][:seat_id]}" }

    .form-actions
      = f.button :submit, "Submit", class: " btn btn-default"

app/views/tickets/show.html.haml
.ticket
  .row
    %h1.show-name=@ticket.show.name
  .row
    %h2.name=@ticket.user_name
  .row
    %p.seat= "Seat: #{@ticket.seat.row} / #{@ticket.seat.place}"
  .row
    %span.code="Ticket code: #{@ticket.id}"
    .barcode
      %img{:alt => "barcode", :src => "http://freebarcodefonts.dobsonsw.com/images/code128bar.jpg"}/
%br/
%br/
%button{:onclick => "window.print();", :type => "button"} Print ticket